language: rust
sudo: false
dist: trusty

cache:
  cargo: true
  directories:
    - .cache

rust:
  - nightly
  - beta
  - stable

script:
  - |
      CARGO_OPTS=()
      if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
        CARGO_OPTS+=("--features" "unstable")
      fi
      cargo build "${CARGO_OPTS[@]}" --workspace --release &&
      cargo run --release --bin euler &&
      cargo test --workspace &&
      cargo bench --workspace &&
      cargo doc --workspace --no-deps
