[package]
name = "seq"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"

[dependencies]
num-integer = "0.1.43"
num-traits = "0.2.12"

[dev-dependencies]
num-bigint = "0.3.0"
