[package]
name = "prime"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
num-integer = "0.1.45"
num-traits = "0.2.15"

[dev-dependencies]
criterion = "0.5.0"
